"""Generate worker/src/speciesXp.ts: species id -> XP, from the bundled species and the region packs.

The worker computes leaderboard XP itself (once per distinct species) so the client never sends XP.
Run after the species data changes: python3 tools/worker/gen_species_xp.py
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
xp = {}
for m in re.finditer(r"\{\s*id:\s*'([^']+)'.*?\bxp:\s*(\d+)", (ROOT / "src/data/bugs.ts").read_text()):
    xp[m.group(1)] = int(m.group(2))
for pack in (ROOT / "packs").glob("*.json"):
    if pack.name == "manifest.json":
        continue
    for b in json.load(open(pack)).get("bugs", []):
        xp[b["id"]] = b["xp"]
body = ",\n".join(f"  {json.dumps(k)}: {v}" for k, v in sorted(xp.items()))
(ROOT / "worker/src/speciesXp.ts").write_text(
    "// Generated by tools/worker/gen_species_xp.py: do not edit.\n"
    "export const SPECIES_XP: Record<string, number> = {\n" + body + ",\n};\n\n"
    "/** XP for a species the table doesn't know (a pack newer than the worker). */\n"
    "export const DEFAULT_SPECIES_XP = 25;\n")
print(len(xp), "species")
