/**
 * Maps the vision model's outputs to app bug IDs.
 *
 * AUTO-GENERATED by training/local/04_export.py — do not edit by hand.
 * Re-run 04_export.py after retraining to keep this in sync.
 *
 * Two lookup shapes:
 *   - SCIENTIFIC_TO_BUG_ID  scientific name  → bug ID  (Gemini path)
 *   - INDEX_TO_BUG_ID       class index → bug ID       (native ONNX/CoreML path)
 *
 * Index ordering matches training/local/checkpoints/class_map_lite.json.
 */

export const SCIENTIFIC_TO_BUG_ID: Readonly<Record<string, string>> = {
  'Palomena prasina':           'gshb',
  'Coccinella septempunctata':  'lady',
  'Bombus hortorum':            'gbee',
  'Apis mellifera':             'hcat',
  'Vespula vulgaris':           'wasp',
  'Vespa crabro':               'horn',
  'Gonepteryx rhamni':          'brim',
  'Bombus terrestris':          'buff',
  'Papilio machaon':            'swal',
  'Anthocharis cardamines':     'orng',
  'Pieris brassicae':           'lwhi',
  'Enallagma cyathigerum':      'bdam',
  'Pieris rapae':               'swhi',
  'Vanessa cardui':             'pntl',
  'Vanessa atalanta':           'radm',
  'Aglais urticae':             'tort',
  'Aglais io':                  'peac',
  'Harmonia axyridis':          'harl',
  'Cetonia aurata':             'rchf',
  'Lucanus cervus':             'stag',
};

/** Index order matches class_map_lite.json produced by train_lite.py. */
export const INDEX_TO_BUG_ID: ReadonlyArray<string> = [
  'gshb', //  0  Palomena prasina
  'lady', //  1  Coccinella septempunctata
  'gbee', //  2  Bombus hortorum
  'hcat', //  3  Apis mellifera
  'wasp', //  4  Vespula vulgaris
  'horn', //  5  Vespa crabro
  'brim', //  6  Gonepteryx rhamni
  'buff', //  7  Bombus terrestris
  'swal', //  8  Papilio machaon
  'orng', //  9  Anthocharis cardamines
  'lwhi', // 10  Pieris brassicae
  'bdam', // 11  Enallagma cyathigerum
  'swhi', // 12  Pieris rapae
  'pntl', // 13  Vanessa cardui
  'radm', // 14  Vanessa atalanta
  'tort', // 15  Aglais urticae
  'peac', // 16  Aglais io
  'harl', // 17  Harmonia axyridis
  'rchf', // 18  Cetonia aurata
  'stag', // 19  Lucanus cervus
];

/** Convenience: look up bug ID by class index, with bounds-check. */
export function indexToBugId(idx: number): string | undefined {
  return INDEX_TO_BUG_ID[idx];
}
