/**
 * Maps the vision model's outputs to app bug IDs.
 *
 * AUTO-GENERATED by training/local/04_export.py — do not edit by hand.
 * Re-run 04_export.py after retraining to keep this in sync.
 *
 * Two lookup shapes:
 *   - SCIENTIFIC_TO_BUG_ID  scientific name  → bug ID  (Gemini path)
 *   - INDEX_TO_BUG_ID       class index → bug ID       (native ONNX/CoreML path)
 *
 * Index ordering matches training/local/checkpoints/class_map_lite.json.
 */

export const SCIENTIFIC_TO_BUG_ID: Readonly<Record<string, string>> = {
  'Bombus hortorum':            'gbee',
  'Vespula vulgaris':           'wasp',
  'Aglais io':                  'peac',
  'Apis mellifera':             'hcat',
  'Harmonia axyridis':          'harl',
  'Vanessa cardui':             'pntl',
  'Vanessa atalanta':           'radm',
  'Anthocharis cardamines':     'orng',
  'Coccinella septempunctata':  'lady',
  'Cetonia aurata':             'rchf',
  'Gonepteryx rhamni':          'brim',
  'Vespa crabro':               'horn',
  'Aglais urticae':             'tort',
  'Pieris brassicae':           'lwhi',
  'Pieris rapae':               'swhi',
  'Papilio machaon':            'swal',
  'Bombus terrestris':          'buff',
  'Lucanus cervus':             'stag',
  'Palomena prasina':           'gshb',
  'Enallagma cyathigerum':      'bdam',
};

/** Index order matches class_map_lite.json produced by train_lite.py. */
export const INDEX_TO_BUG_ID: ReadonlyArray<string> = [
  'gbee', //  0  Bombus hortorum
  'wasp', //  1  Vespula vulgaris
  'peac', //  2  Aglais io
  'hcat', //  3  Apis mellifera
  'harl', //  4  Harmonia axyridis
  'pntl', //  5  Vanessa cardui
  'radm', //  6  Vanessa atalanta
  'orng', //  7  Anthocharis cardamines
  'lady', //  8  Coccinella septempunctata
  'rchf', //  9  Cetonia aurata
  'brim', // 10  Gonepteryx rhamni
  'horn', // 11  Vespa crabro
  'tort', // 12  Aglais urticae
  'lwhi', // 13  Pieris brassicae
  'swhi', // 14  Pieris rapae
  'swal', // 15  Papilio machaon
  'buff', // 16  Bombus terrestris
  'stag', // 17  Lucanus cervus
  'gshb', // 18  Palomena prasina
  'bdam', // 19  Enallagma cyathigerum
];

/** Convenience: look up bug ID by class index, with bounds-check. */
export function indexToBugId(idx: number): string | undefined {
  return INDEX_TO_BUG_ID[idx];
}
